/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppUserRole = { 'FIRSTY_CONSULTANT' : null } |
  { 'FIRSTY_ADMIN' : null } |
  { 'OWNER_ADMIN' : null } |
  { 'MEMBER' : null };
export interface Contact {
  'id' : string,
  'orgId' : OrgId,
  'name' : string,
  'createdBy' : Principal,
  'email' : string,
  'phone' : string,
}
export type OrgId = string;
export interface Organization {
  'id' : OrgId,
  'name' : string,
  'createdAt' : bigint,
  'createdBy' : Principal,
}
export interface UserProfile {
  'appRole' : AppUserRole,
  'email' : string,
  'currentOrgId' : [] | [OrgId],
  'lastName' : string,
  'firstName' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createContact' : ActorMethod<[Contact], undefined>,
  'createOrganization' : ActorMethod<[string, bigint], OrgId>,
  'deleteContact' : ActorMethod<[string], undefined>,
  'deleteOrganization' : ActorMethod<[OrgId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContact' : ActorMethod<[string], [] | [Contact]>,
  'getOrganization' : ActorMethod<[OrgId], [] | [Organization]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listContacts' : ActorMethod<[OrgId], Array<Contact>>,
  'listOrganizations' : ActorMethod<[], Array<Organization>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateContact' : ActorMethod<[string, string, string, string], undefined>,
  'updateOrganization' : ActorMethod<[OrgId, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];