/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const OrgId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Activity = IDL.Record({
  'id' : IDL.Text,
  'orgId' : OrgId,
  'relatedProject' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdBy' : IDL.Principal,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Opt(IDL.Int),
});
export const Contact = IDL.Record({
  'id' : IDL.Text,
  'orgId' : OrgId,
  'name' : IDL.Text,
  'createdBy' : IDL.Principal,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const Contract = IDL.Record({
  'id' : IDL.Text,
  'endDate' : IDL.Opt(IDL.Int),
  'value' : IDL.Nat,
  'orgId' : OrgId,
  'name' : IDL.Text,
  'createdBy' : IDL.Principal,
  'startDate' : IDL.Int,
});
export const DealStage = IDL.Variant({
  'prospecting' : IDL.Null,
  'closedWon' : IDL.Null,
  'negotiation' : IDL.Null,
  'closedLost' : IDL.Null,
});
export const Deal = IDL.Record({
  'id' : IDL.Text,
  'value' : IDL.Nat,
  'orgId' : OrgId,
  'name' : IDL.Text,
  'createdBy' : IDL.Principal,
  'stage' : DealStage,
});
export const FinanceTransaction = IDL.Record({
  'id' : IDL.Text,
  'orgId' : OrgId,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
  'amount' : IDL.Nat,
});
export const NpsCampaign = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'orgId' : OrgId,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
});
export const ProjectPhase = IDL.Variant({
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
  'planning' : IDL.Null,
});
export const Project = IDL.Record({
  'id' : IDL.Text,
  'orgId' : OrgId,
  'name' : IDL.Text,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
  'phase' : ProjectPhase,
});
export const Report = IDL.Record({
  'id' : IDL.Text,
  'orgId' : OrgId,
  'period' : IDL.Text,
  'generatedAt' : IDL.Int,
  'generatedBy' : IDL.Principal,
  'reportType' : IDL.Text,
  'format' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'email' : IDL.Text,
  'currentOrgId' : IDL.Opt(OrgId),
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const DocumentCategory = IDL.Variant({
  'projectDocs' : IDL.Null,
  'other' : IDL.Null,
  'marketing' : IDL.Null,
  'legal' : IDL.Null,
  'presentations' : IDL.Null,
  'contracts' : IDL.Null,
  'reports' : IDL.Null,
  'invoices' : IDL.Null,
  'proposals' : IDL.Null,
  'mediaAssets' : IDL.Null,
});
export const Document = IDL.Record({
  'id' : IDL.Text,
  'orgId' : OrgId,
  'file' : ExternalBlob,
  'name' : IDL.Text,
  'category' : DocumentCategory,
  'uploadedAt' : IDL.Int,
  'uploadedBy' : IDL.Principal,
});
export const Organization = IDL.Record({
  'id' : OrgId,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
});
export const TeamInvitation = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'orgId' : OrgId,
  'invitedAt' : IDL.Int,
  'invitedBy' : IDL.Principal,
  'inviteeIdentifier' : IDL.Text,
});
export const DocumentUploadInput = IDL.Record({
  'orgId' : OrgId,
  'file' : ExternalBlob,
  'name' : IDL.Text,
  'category' : DocumentCategory,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMemberToOrg' : IDL.Func([IDL.Principal, OrgId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createActivity' : IDL.Func([Activity], [], []),
  'createContact' : IDL.Func([Contact], [], []),
  'createContract' : IDL.Func([Contract], [], []),
  'createDeal' : IDL.Func([Deal], [], []),
  'createFinanceTransaction' : IDL.Func([FinanceTransaction], [], []),
  'createNpsCampaign' : IDL.Func([NpsCampaign], [], []),
  'createOrganization' : IDL.Func([IDL.Text, IDL.Int], [OrgId], []),
  'createProject' : IDL.Func([Project], [], []),
  'generateReport' : IDL.Func([Report], [], []),
  'getActivity' : IDL.Func([IDL.Text], [IDL.Opt(Activity)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContact' : IDL.Func([IDL.Text], [IDL.Opt(Contact)], ['query']),
  'getContract' : IDL.Func([IDL.Text], [IDL.Opt(Contract)], ['query']),
  'getDeal' : IDL.Func([IDL.Text], [IDL.Opt(Deal)], ['query']),
  'getDocument' : IDL.Func([IDL.Text], [IDL.Opt(Document)], ['query']),
  'getFinanceTransaction' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(FinanceTransaction)],
      ['query'],
    ),
  'getNpsCampaign' : IDL.Func([IDL.Text], [IDL.Opt(NpsCampaign)], ['query']),
  'getOrganization' : IDL.Func([OrgId], [IDL.Opt(Organization)], ['query']),
  'getProject' : IDL.Func([IDL.Text], [IDL.Opt(Project)], ['query']),
  'getReport' : IDL.Func([IDL.Text], [IDL.Opt(Report)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'inviteTeamMember' : IDL.Func([TeamInvitation], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listActivities' : IDL.Func([OrgId], [IDL.Vec(Activity)], ['query']),
  'listContacts' : IDL.Func([OrgId], [IDL.Vec(Contact)], ['query']),
  'listContracts' : IDL.Func([OrgId], [IDL.Vec(Contract)], ['query']),
  'listDeals' : IDL.Func([OrgId], [IDL.Vec(Deal)], ['query']),
  'listDocuments' : IDL.Func([OrgId], [IDL.Vec(Document)], ['query']),
  'listFinanceTransactions' : IDL.Func(
      [OrgId],
      [IDL.Vec(FinanceTransaction)],
      ['query'],
    ),
  'listNpsCampaigns' : IDL.Func([OrgId], [IDL.Vec(NpsCampaign)], ['query']),
  'listOrgMembers' : IDL.Func([OrgId], [IDL.Vec(IDL.Principal)], ['query']),
  'listProjects' : IDL.Func([OrgId], [IDL.Vec(Project)], ['query']),
  'listReports' : IDL.Func([OrgId], [IDL.Vec(Report)], ['query']),
  'listTeamInvitations' : IDL.Func(
      [OrgId],
      [IDL.Vec(TeamInvitation)],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'uploadDocument' : IDL.Func([DocumentUploadInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const OrgId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Activity = IDL.Record({
    'id' : IDL.Text,
    'orgId' : OrgId,
    'relatedProject' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdBy' : IDL.Principal,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Opt(IDL.Int),
  });
  const Contact = IDL.Record({
    'id' : IDL.Text,
    'orgId' : OrgId,
    'name' : IDL.Text,
    'createdBy' : IDL.Principal,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Contract = IDL.Record({
    'id' : IDL.Text,
    'endDate' : IDL.Opt(IDL.Int),
    'value' : IDL.Nat,
    'orgId' : OrgId,
    'name' : IDL.Text,
    'createdBy' : IDL.Principal,
    'startDate' : IDL.Int,
  });
  const DealStage = IDL.Variant({
    'prospecting' : IDL.Null,
    'closedWon' : IDL.Null,
    'negotiation' : IDL.Null,
    'closedLost' : IDL.Null,
  });
  const Deal = IDL.Record({
    'id' : IDL.Text,
    'value' : IDL.Nat,
    'orgId' : OrgId,
    'name' : IDL.Text,
    'createdBy' : IDL.Principal,
    'stage' : DealStage,
  });
  const FinanceTransaction = IDL.Record({
    'id' : IDL.Text,
    'orgId' : OrgId,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const NpsCampaign = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'orgId' : OrgId,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
  });
  const ProjectPhase = IDL.Variant({
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
    'planning' : IDL.Null,
  });
  const Project = IDL.Record({
    'id' : IDL.Text,
    'orgId' : OrgId,
    'name' : IDL.Text,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'phase' : ProjectPhase,
  });
  const Report = IDL.Record({
    'id' : IDL.Text,
    'orgId' : OrgId,
    'period' : IDL.Text,
    'generatedAt' : IDL.Int,
    'generatedBy' : IDL.Principal,
    'reportType' : IDL.Text,
    'format' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'email' : IDL.Text,
    'currentOrgId' : IDL.Opt(OrgId),
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const DocumentCategory = IDL.Variant({
    'projectDocs' : IDL.Null,
    'other' : IDL.Null,
    'marketing' : IDL.Null,
    'legal' : IDL.Null,
    'presentations' : IDL.Null,
    'contracts' : IDL.Null,
    'reports' : IDL.Null,
    'invoices' : IDL.Null,
    'proposals' : IDL.Null,
    'mediaAssets' : IDL.Null,
  });
  const Document = IDL.Record({
    'id' : IDL.Text,
    'orgId' : OrgId,
    'file' : ExternalBlob,
    'name' : IDL.Text,
    'category' : DocumentCategory,
    'uploadedAt' : IDL.Int,
    'uploadedBy' : IDL.Principal,
  });
  const Organization = IDL.Record({
    'id' : OrgId,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
  });
  const TeamInvitation = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'orgId' : OrgId,
    'invitedAt' : IDL.Int,
    'invitedBy' : IDL.Principal,
    'inviteeIdentifier' : IDL.Text,
  });
  const DocumentUploadInput = IDL.Record({
    'orgId' : OrgId,
    'file' : ExternalBlob,
    'name' : IDL.Text,
    'category' : DocumentCategory,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMemberToOrg' : IDL.Func([IDL.Principal, OrgId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createActivity' : IDL.Func([Activity], [], []),
    'createContact' : IDL.Func([Contact], [], []),
    'createContract' : IDL.Func([Contract], [], []),
    'createDeal' : IDL.Func([Deal], [], []),
    'createFinanceTransaction' : IDL.Func([FinanceTransaction], [], []),
    'createNpsCampaign' : IDL.Func([NpsCampaign], [], []),
    'createOrganization' : IDL.Func([IDL.Text, IDL.Int], [OrgId], []),
    'createProject' : IDL.Func([Project], [], []),
    'generateReport' : IDL.Func([Report], [], []),
    'getActivity' : IDL.Func([IDL.Text], [IDL.Opt(Activity)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContact' : IDL.Func([IDL.Text], [IDL.Opt(Contact)], ['query']),
    'getContract' : IDL.Func([IDL.Text], [IDL.Opt(Contract)], ['query']),
    'getDeal' : IDL.Func([IDL.Text], [IDL.Opt(Deal)], ['query']),
    'getDocument' : IDL.Func([IDL.Text], [IDL.Opt(Document)], ['query']),
    'getFinanceTransaction' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(FinanceTransaction)],
        ['query'],
      ),
    'getNpsCampaign' : IDL.Func([IDL.Text], [IDL.Opt(NpsCampaign)], ['query']),
    'getOrganization' : IDL.Func([OrgId], [IDL.Opt(Organization)], ['query']),
    'getProject' : IDL.Func([IDL.Text], [IDL.Opt(Project)], ['query']),
    'getReport' : IDL.Func([IDL.Text], [IDL.Opt(Report)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'inviteTeamMember' : IDL.Func([TeamInvitation], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listActivities' : IDL.Func([OrgId], [IDL.Vec(Activity)], ['query']),
    'listContacts' : IDL.Func([OrgId], [IDL.Vec(Contact)], ['query']),
    'listContracts' : IDL.Func([OrgId], [IDL.Vec(Contract)], ['query']),
    'listDeals' : IDL.Func([OrgId], [IDL.Vec(Deal)], ['query']),
    'listDocuments' : IDL.Func([OrgId], [IDL.Vec(Document)], ['query']),
    'listFinanceTransactions' : IDL.Func(
        [OrgId],
        [IDL.Vec(FinanceTransaction)],
        ['query'],
      ),
    'listNpsCampaigns' : IDL.Func([OrgId], [IDL.Vec(NpsCampaign)], ['query']),
    'listOrgMembers' : IDL.Func([OrgId], [IDL.Vec(IDL.Principal)], ['query']),
    'listProjects' : IDL.Func([OrgId], [IDL.Vec(Project)], ['query']),
    'listReports' : IDL.Func([OrgId], [IDL.Vec(Report)], ['query']),
    'listTeamInvitations' : IDL.Func(
        [OrgId],
        [IDL.Vec(TeamInvitation)],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'uploadDocument' : IDL.Func([DocumentUploadInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };