/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Activity {
  'id' : string,
  'orgId' : OrgId,
  'relatedProject' : [] | [string],
  'name' : string,
  'createdBy' : Principal,
  'completed' : boolean,
  'dueDate' : [] | [bigint],
}
export interface Contact {
  'id' : string,
  'orgId' : OrgId,
  'name' : string,
  'createdBy' : Principal,
  'email' : string,
  'phone' : string,
}
export interface Contract {
  'id' : string,
  'endDate' : [] | [bigint],
  'value' : bigint,
  'orgId' : OrgId,
  'name' : string,
  'createdBy' : Principal,
  'startDate' : bigint,
}
export interface Deal {
  'id' : string,
  'value' : bigint,
  'orgId' : OrgId,
  'name' : string,
  'createdBy' : Principal,
  'stage' : DealStage,
}
export type DealStage = { 'prospecting' : null } |
  { 'closedWon' : null } |
  { 'negotiation' : null } |
  { 'closedLost' : null };
export interface Document {
  'id' : string,
  'orgId' : OrgId,
  'file' : ExternalBlob,
  'name' : string,
  'category' : DocumentCategory,
  'uploadedAt' : bigint,
  'uploadedBy' : Principal,
}
export type DocumentCategory = { 'projectDocs' : null } |
  { 'other' : null } |
  { 'marketing' : null } |
  { 'legal' : null } |
  { 'presentations' : null } |
  { 'contracts' : null } |
  { 'reports' : null } |
  { 'invoices' : null } |
  { 'proposals' : null } |
  { 'mediaAssets' : null };
export interface DocumentUploadInput {
  'orgId' : OrgId,
  'file' : ExternalBlob,
  'name' : string,
  'category' : DocumentCategory,
}
export type ExternalBlob = Uint8Array;
export interface FinanceTransaction {
  'id' : string,
  'orgId' : OrgId,
  'createdAt' : bigint,
  'createdBy' : Principal,
  'description' : string,
  'amount' : bigint,
}
export interface NpsCampaign {
  'id' : string,
  'status' : string,
  'orgId' : OrgId,
  'name' : string,
  'createdAt' : bigint,
  'createdBy' : Principal,
}
export type OrgId = string;
export interface Organization {
  'id' : OrgId,
  'name' : string,
  'createdAt' : bigint,
  'createdBy' : Principal,
}
export interface Project {
  'id' : string,
  'orgId' : OrgId,
  'name' : string,
  'createdBy' : Principal,
  'description' : string,
  'phase' : ProjectPhase,
}
export type ProjectPhase = { 'completed' : null } |
  { 'inProgress' : null } |
  { 'planning' : null };
export interface Report {
  'id' : string,
  'orgId' : OrgId,
  'period' : string,
  'generatedAt' : bigint,
  'generatedBy' : Principal,
  'reportType' : string,
  'format' : string,
}
export interface TeamInvitation {
  'id' : string,
  'status' : string,
  'orgId' : OrgId,
  'invitedAt' : bigint,
  'invitedBy' : Principal,
  'inviteeIdentifier' : string,
}
export interface UserProfile {
  'email' : string,
  'currentOrgId' : [] | [OrgId],
  'lastName' : string,
  'firstName' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMemberToOrg' : ActorMethod<[Principal, OrgId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createActivity' : ActorMethod<[Activity], undefined>,
  'createContact' : ActorMethod<[Contact], undefined>,
  'createContract' : ActorMethod<[Contract], undefined>,
  'createDeal' : ActorMethod<[Deal], undefined>,
  'createFinanceTransaction' : ActorMethod<[FinanceTransaction], undefined>,
  'createNpsCampaign' : ActorMethod<[NpsCampaign], undefined>,
  'createOrganization' : ActorMethod<[string, bigint], OrgId>,
  'createProject' : ActorMethod<[Project], undefined>,
  'generateReport' : ActorMethod<[Report], undefined>,
  'getActivity' : ActorMethod<[string], [] | [Activity]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContact' : ActorMethod<[string], [] | [Contact]>,
  'getContract' : ActorMethod<[string], [] | [Contract]>,
  'getDeal' : ActorMethod<[string], [] | [Deal]>,
  'getDocument' : ActorMethod<[string], [] | [Document]>,
  'getFinanceTransaction' : ActorMethod<[string], [] | [FinanceTransaction]>,
  'getNpsCampaign' : ActorMethod<[string], [] | [NpsCampaign]>,
  'getOrganization' : ActorMethod<[OrgId], [] | [Organization]>,
  'getProject' : ActorMethod<[string], [] | [Project]>,
  'getReport' : ActorMethod<[string], [] | [Report]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'inviteTeamMember' : ActorMethod<[TeamInvitation], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listActivities' : ActorMethod<[OrgId], Array<Activity>>,
  'listContacts' : ActorMethod<[OrgId], Array<Contact>>,
  'listContracts' : ActorMethod<[OrgId], Array<Contract>>,
  'listDeals' : ActorMethod<[OrgId], Array<Deal>>,
  'listDocuments' : ActorMethod<[OrgId], Array<Document>>,
  'listFinanceTransactions' : ActorMethod<[OrgId], Array<FinanceTransaction>>,
  'listNpsCampaigns' : ActorMethod<[OrgId], Array<NpsCampaign>>,
  'listOrgMembers' : ActorMethod<[OrgId], Array<Principal>>,
  'listProjects' : ActorMethod<[OrgId], Array<Project>>,
  'listReports' : ActorMethod<[OrgId], Array<Report>>,
  'listTeamInvitations' : ActorMethod<[OrgId], Array<TeamInvitation>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'uploadDocument' : ActorMethod<[DocumentUploadInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];