/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrgId = IDL.Text;
export const Contact = IDL.Record({
  'id' : IDL.Text,
  'orgId' : OrgId,
  'name' : IDL.Text,
  'createdBy' : IDL.Principal,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const AppUserRole = IDL.Variant({
  'FIRSTY_CONSULTANT' : IDL.Null,
  'FIRSTY_ADMIN' : IDL.Null,
  'OWNER_ADMIN' : IDL.Null,
  'MEMBER' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'appRole' : AppUserRole,
  'email' : IDL.Text,
  'currentOrgId' : IDL.Opt(OrgId),
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const Organization = IDL.Record({
  'id' : OrgId,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createContact' : IDL.Func([Contact], [], []),
  'createOrganization' : IDL.Func([IDL.Text, IDL.Int], [OrgId], []),
  'deleteContact' : IDL.Func([IDL.Text], [], []),
  'deleteOrganization' : IDL.Func([OrgId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContact' : IDL.Func([IDL.Text], [IDL.Opt(Contact)], ['query']),
  'getOrganization' : IDL.Func([OrgId], [IDL.Opt(Organization)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listContacts' : IDL.Func([OrgId], [IDL.Vec(Contact)], ['query']),
  'listOrganizations' : IDL.Func([], [IDL.Vec(Organization)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateOrganization' : IDL.Func([OrgId, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrgId = IDL.Text;
  const Contact = IDL.Record({
    'id' : IDL.Text,
    'orgId' : OrgId,
    'name' : IDL.Text,
    'createdBy' : IDL.Principal,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const AppUserRole = IDL.Variant({
    'FIRSTY_CONSULTANT' : IDL.Null,
    'FIRSTY_ADMIN' : IDL.Null,
    'OWNER_ADMIN' : IDL.Null,
    'MEMBER' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'appRole' : AppUserRole,
    'email' : IDL.Text,
    'currentOrgId' : IDL.Opt(OrgId),
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const Organization = IDL.Record({
    'id' : OrgId,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createContact' : IDL.Func([Contact], [], []),
    'createOrganization' : IDL.Func([IDL.Text, IDL.Int], [OrgId], []),
    'deleteContact' : IDL.Func([IDL.Text], [], []),
    'deleteOrganization' : IDL.Func([OrgId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContact' : IDL.Func([IDL.Text], [IDL.Opt(Contact)], ['query']),
    'getOrganization' : IDL.Func([OrgId], [IDL.Opt(Organization)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listContacts' : IDL.Func([OrgId], [IDL.Vec(Contact)], ['query']),
    'listOrganizations' : IDL.Func([], [IDL.Vec(Organization)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateOrganization' : IDL.Func([OrgId, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };