/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type OrgId = string;
export interface Contact {
    id: string;
    orgId: OrgId;
    name: string;
    createdBy: Principal;
    email: string;
    phone: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface NpsCampaign {
    id: string;
    status: string;
    orgId: OrgId;
    name: string;
    createdAt: bigint;
    createdBy: Principal;
}
export interface DocumentUploadInput {
    orgId: OrgId;
    file: ExternalBlob;
    name: string;
    category: DocumentCategory;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Report {
    id: string;
    orgId: OrgId;
    period: string;
    generatedAt: bigint;
    generatedBy: Principal;
    reportType: string;
    format: string;
}
export interface Document {
    id: string;
    orgId: OrgId;
    file: ExternalBlob;
    name: string;
    category: DocumentCategory;
    uploadedAt: bigint;
    uploadedBy: Principal;
}
export interface TeamInvitation {
    id: string;
    status: string;
    orgId: OrgId;
    invitedAt: bigint;
    invitedBy: Principal;
    inviteeIdentifier: string;
}
export interface Activity {
    id: string;
    orgId: OrgId;
    relatedProject?: string;
    name: string;
    createdBy: Principal;
    completed: boolean;
    dueDate?: bigint;
}
export interface Deal {
    id: string;
    value: bigint;
    orgId: OrgId;
    name: string;
    createdBy: Principal;
    stage: DealStage;
}
export interface FinanceTransaction {
    id: string;
    orgId: OrgId;
    createdAt: bigint;
    createdBy: Principal;
    description: string;
    amount: bigint;
}
export interface Contract {
    id: string;
    endDate?: bigint;
    value: bigint;
    orgId: OrgId;
    name: string;
    createdBy: Principal;
    startDate: bigint;
}
export interface Project {
    id: string;
    orgId: OrgId;
    name: string;
    createdBy: Principal;
    description: string;
    phase: ProjectPhase;
}
export interface Organization {
    id: OrgId;
    name: string;
    createdAt: bigint;
    createdBy: Principal;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    email: string;
    currentOrgId?: OrgId;
    lastName: string;
    firstName: string;
}
export enum DealStage {
    prospecting = "prospecting",
    closedWon = "closedWon",
    negotiation = "negotiation",
    closedLost = "closedLost"
}
export enum DocumentCategory {
    projectDocs = "projectDocs",
    other = "other",
    marketing = "marketing",
    legal = "legal",
    presentations = "presentations",
    contracts = "contracts",
    reports = "reports",
    invoices = "invoices",
    proposals = "proposals",
    mediaAssets = "mediaAssets"
}
export enum ProjectPhase {
    completed = "completed",
    inProgress = "inProgress",
    planning = "planning"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addMemberToOrg(user: Principal, orgId: OrgId): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createActivity(activity: Activity): Promise<void>;
    createContact(contact: Contact): Promise<void>;
    createContract(contract: Contract): Promise<void>;
    createDeal(deal: Deal): Promise<void>;
    createFinanceTransaction(transaction: FinanceTransaction): Promise<void>;
    createNpsCampaign(campaign: NpsCampaign): Promise<void>;
    createOrganization(name: string, timestamp: bigint): Promise<OrgId>;
    createProject(project: Project): Promise<void>;
    generateReport(report: Report): Promise<void>;
    getActivity(id: string): Promise<Activity | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContact(id: string): Promise<Contact | null>;
    getContract(id: string): Promise<Contract | null>;
    getDeal(id: string): Promise<Deal | null>;
    getDocument(id: string): Promise<Document | null>;
    getFinanceTransaction(id: string): Promise<FinanceTransaction | null>;
    getNpsCampaign(id: string): Promise<NpsCampaign | null>;
    getOrganization(orgId: OrgId): Promise<Organization | null>;
    getProject(id: string): Promise<Project | null>;
    getReport(id: string): Promise<Report | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    inviteTeamMember(invitation: TeamInvitation): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    listActivities(orgId: OrgId): Promise<Array<Activity>>;
    listContacts(orgId: OrgId): Promise<Array<Contact>>;
    listContracts(orgId: OrgId): Promise<Array<Contract>>;
    listDeals(orgId: OrgId): Promise<Array<Deal>>;
    listDocuments(orgId: OrgId): Promise<Array<Document>>;
    listFinanceTransactions(orgId: OrgId): Promise<Array<FinanceTransaction>>;
    listNpsCampaigns(orgId: OrgId): Promise<Array<NpsCampaign>>;
    listOrgMembers(orgId: OrgId): Promise<Array<Principal>>;
    listProjects(orgId: OrgId): Promise<Array<Project>>;
    listReports(orgId: OrgId): Promise<Array<Report>>;
    listTeamInvitations(orgId: OrgId): Promise<Array<TeamInvitation>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    uploadDocument(input: DocumentUploadInput): Promise<void>;
}
import type { Activity as _Activity, Contact as _Contact, Contract as _Contract, Deal as _Deal, DealStage as _DealStage, Document as _Document, DocumentCategory as _DocumentCategory, DocumentUploadInput as _DocumentUploadInput, ExternalBlob as _ExternalBlob, FinanceTransaction as _FinanceTransaction, NpsCampaign as _NpsCampaign, OrgId as _OrgId, Organization as _Organization, Project as _Project, ProjectPhase as _ProjectPhase, Report as _Report, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addMemberToOrg(arg0: Principal, arg1: OrgId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMemberToOrg(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMemberToOrg(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createActivity(arg0: Activity): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createActivity(to_candid_Activity_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createActivity(to_candid_Activity_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createContact(arg0: Contact): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createContact(arg0);
            return result;
        }
    }
    async createContract(arg0: Contract): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createContract(to_candid_Contract_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createContract(to_candid_Contract_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createDeal(arg0: Deal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createDeal(to_candid_Deal_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDeal(to_candid_Deal_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createFinanceTransaction(arg0: FinanceTransaction): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createFinanceTransaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFinanceTransaction(arg0);
            return result;
        }
    }
    async createNpsCampaign(arg0: NpsCampaign): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createNpsCampaign(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNpsCampaign(arg0);
            return result;
        }
    }
    async createOrganization(arg0: string, arg1: bigint): Promise<OrgId> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrganization(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrganization(arg0, arg1);
            return result;
        }
    }
    async createProject(arg0: Project): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(to_candid_Project_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(to_candid_Project_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async generateReport(arg0: Report): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.generateReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateReport(arg0);
            return result;
        }
    }
    async getActivity(arg0: string): Promise<Activity | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivity(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivity(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContact(arg0: string): Promise<Contact | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getContact(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContact(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContract(arg0: string): Promise<Contract | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getContract(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContract(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDeal(arg0: string): Promise<Deal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeal(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeal(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDocument(arg0: string): Promise<Document | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocument(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocument(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFinanceTransaction(arg0: string): Promise<FinanceTransaction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFinanceTransaction(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFinanceTransaction(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNpsCampaign(arg0: string): Promise<NpsCampaign | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNpsCampaign(arg0);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNpsCampaign(arg0);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrganization(arg0: OrgId): Promise<Organization | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrganization(arg0);
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrganization(arg0);
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProject(arg0: string): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReport(arg0: string): Promise<Report | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReport(arg0);
                return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReport(arg0);
            return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async inviteTeamMember(arg0: TeamInvitation): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.inviteTeamMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.inviteTeamMember(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listActivities(arg0: OrgId): Promise<Array<Activity>> {
        if (this.processError) {
            try {
                const result = await this.actor.listActivities(arg0);
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listActivities(arg0);
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async listContacts(arg0: OrgId): Promise<Array<Contact>> {
        if (this.processError) {
            try {
                const result = await this.actor.listContacts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listContacts(arg0);
            return result;
        }
    }
    async listContracts(arg0: OrgId): Promise<Array<Contract>> {
        if (this.processError) {
            try {
                const result = await this.actor.listContracts(arg0);
                return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listContracts(arg0);
            return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDeals(arg0: OrgId): Promise<Array<Deal>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDeals(arg0);
                return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDeals(arg0);
            return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDocuments(arg0: OrgId): Promise<Array<Document>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDocuments(arg0);
                return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDocuments(arg0);
            return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFinanceTransactions(arg0: OrgId): Promise<Array<FinanceTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFinanceTransactions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFinanceTransactions(arg0);
            return result;
        }
    }
    async listNpsCampaigns(arg0: OrgId): Promise<Array<NpsCampaign>> {
        if (this.processError) {
            try {
                const result = await this.actor.listNpsCampaigns(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listNpsCampaigns(arg0);
            return result;
        }
    }
    async listOrgMembers(arg0: OrgId): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.listOrgMembers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listOrgMembers(arg0);
            return result;
        }
    }
    async listProjects(arg0: OrgId): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProjects(arg0);
                return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProjects(arg0);
            return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async listReports(arg0: OrgId): Promise<Array<Report>> {
        if (this.processError) {
            try {
                const result = await this.actor.listReports(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listReports(arg0);
            return result;
        }
    }
    async listTeamInvitations(arg0: OrgId): Promise<Array<TeamInvitation>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTeamInvitations(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTeamInvitations(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n62(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n62(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async uploadDocument(arg0: DocumentUploadInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadDocument(await to_candid_DocumentUploadInput_n64(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadDocument(await to_candid_DocumentUploadInput_n64(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Activity_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Activity): Activity {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Contract_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Contract): Contract {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_DealStage_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DealStage): DealStage {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_Deal_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Deal): Deal {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_DocumentCategory_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DocumentCategory): DocumentCategory {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
async function from_candid_Document_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Document): Promise<Document> {
    return await from_candid_record_n44(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_ProjectPhase_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectPhase): ProjectPhase {
    return from_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function from_candid_Project_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Activity]): Activity | null {
    return value.length === 0 ? null : from_candid_Activity_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OrgId]): OrgId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Contact]): Contact | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Contract]): Contract | null {
    return value.length === 0 ? null : from_candid_Contract_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Deal]): Deal | null {
    return value.length === 0 ? null : from_candid_Deal_n38(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Document]): Promise<Document | null> {
    return value.length === 0 ? null : await from_candid_Document_n43(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FinanceTransaction]): FinanceTransaction | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NpsCampaign]): NpsCampaign | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Organization]): Organization | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Project]): Project | null {
    return value.length === 0 ? null : from_candid_Project_n52(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Report]): Report | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    orgId: _OrgId;
    relatedProject: [] | [string];
    name: string;
    createdBy: Principal;
    completed: boolean;
    dueDate: [] | [bigint];
}): {
    id: string;
    orgId: OrgId;
    relatedProject?: string;
    name: string;
    createdBy: Principal;
    completed: boolean;
    dueDate?: bigint;
} {
    return {
        id: value.id,
        orgId: value.orgId,
        relatedProject: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.relatedProject)),
        name: value.name,
        createdBy: value.createdBy,
        completed: value.completed,
        dueDate: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.dueDate))
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    email: string;
    currentOrgId: [] | [_OrgId];
    lastName: string;
    firstName: string;
}): {
    email: string;
    currentOrgId?: OrgId;
    lastName: string;
    firstName: string;
} {
    return {
        email: value.email,
        currentOrgId: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.currentOrgId)),
        lastName: value.lastName,
        firstName: value.firstName
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    endDate: [] | [bigint];
    value: bigint;
    orgId: _OrgId;
    name: string;
    createdBy: Principal;
    startDate: bigint;
}): {
    id: string;
    endDate?: bigint;
    value: bigint;
    orgId: OrgId;
    name: string;
    createdBy: Principal;
    startDate: bigint;
} {
    return {
        id: value.id,
        endDate: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.endDate)),
        value: value.value,
        orgId: value.orgId,
        name: value.name,
        createdBy: value.createdBy,
        startDate: value.startDate
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    value: bigint;
    orgId: _OrgId;
    name: string;
    createdBy: Principal;
    stage: _DealStage;
}): {
    id: string;
    value: bigint;
    orgId: OrgId;
    name: string;
    createdBy: Principal;
    stage: DealStage;
} {
    return {
        id: value.id,
        value: value.value,
        orgId: value.orgId,
        name: value.name,
        createdBy: value.createdBy,
        stage: from_candid_DealStage_n40(_uploadFile, _downloadFile, value.stage)
    };
}
async function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    orgId: _OrgId;
    file: _ExternalBlob;
    name: string;
    category: _DocumentCategory;
    uploadedAt: bigint;
    uploadedBy: Principal;
}): Promise<{
    id: string;
    orgId: OrgId;
    file: ExternalBlob;
    name: string;
    category: DocumentCategory;
    uploadedAt: bigint;
    uploadedBy: Principal;
}> {
    return {
        id: value.id,
        orgId: value.orgId,
        file: await from_candid_ExternalBlob_n45(_uploadFile, _downloadFile, value.file),
        name: value.name,
        category: from_candid_DocumentCategory_n46(_uploadFile, _downloadFile, value.category),
        uploadedAt: value.uploadedAt,
        uploadedBy: value.uploadedBy
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    orgId: _OrgId;
    name: string;
    createdBy: Principal;
    description: string;
    phase: _ProjectPhase;
}): {
    id: string;
    orgId: OrgId;
    name: string;
    createdBy: Principal;
    description: string;
    phase: ProjectPhase;
} {
    return {
        id: value.id,
        orgId: value.orgId,
        name: value.name,
        createdBy: value.createdBy,
        description: value.description,
        phase: from_candid_ProjectPhase_n54(_uploadFile, _downloadFile, value.phase)
    };
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    prospecting: null;
} | {
    closedWon: null;
} | {
    negotiation: null;
} | {
    closedLost: null;
}): DealStage {
    return "prospecting" in value ? DealStage.prospecting : "closedWon" in value ? DealStage.closedWon : "negotiation" in value ? DealStage.negotiation : "closedLost" in value ? DealStage.closedLost : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    projectDocs: null;
} | {
    other: null;
} | {
    marketing: null;
} | {
    legal: null;
} | {
    presentations: null;
} | {
    contracts: null;
} | {
    reports: null;
} | {
    invoices: null;
} | {
    proposals: null;
} | {
    mediaAssets: null;
}): DocumentCategory {
    return "projectDocs" in value ? DocumentCategory.projectDocs : "other" in value ? DocumentCategory.other : "marketing" in value ? DocumentCategory.marketing : "legal" in value ? DocumentCategory.legal : "presentations" in value ? DocumentCategory.presentations : "contracts" in value ? DocumentCategory.contracts : "reports" in value ? DocumentCategory.reports : "invoices" in value ? DocumentCategory.invoices : "proposals" in value ? DocumentCategory.proposals : "mediaAssets" in value ? DocumentCategory.mediaAssets : value;
}
function from_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: null;
} | {
    inProgress: null;
} | {
    planning: null;
}): ProjectPhase {
    return "completed" in value ? ProjectPhase.completed : "inProgress" in value ? ProjectPhase.inProgress : "planning" in value ? ProjectPhase.planning : value;
}
function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Activity>): Array<Activity> {
    return value.map((x)=>from_candid_Activity_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Contract>): Array<Contract> {
    return value.map((x)=>from_candid_Contract_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Deal>): Array<Deal> {
    return value.map((x)=>from_candid_Deal_n38(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Document>): Promise<Array<Document>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Document_n43(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n52(_uploadFile, _downloadFile, x));
}
function to_candid_Activity_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Activity): _Activity {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Contract_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Contract): _Contract {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_DealStage_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DealStage): _DealStage {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_Deal_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Deal): _Deal {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_DocumentCategory_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentCategory): _DocumentCategory {
    return to_candid_variant_n68(_uploadFile, _downloadFile, value);
}
async function to_candid_DocumentUploadInput_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentUploadInput): Promise<_DocumentUploadInput> {
    return await to_candid_record_n65(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_ProjectPhase_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectPhase): _ProjectPhase {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_Project_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Project): _Project {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n63(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    orgId: OrgId;
    relatedProject?: string;
    name: string;
    createdBy: Principal;
    completed: boolean;
    dueDate?: bigint;
}): {
    id: string;
    orgId: _OrgId;
    relatedProject: [] | [string];
    name: string;
    createdBy: Principal;
    completed: boolean;
    dueDate: [] | [bigint];
} {
    return {
        id: value.id,
        orgId: value.orgId,
        relatedProject: value.relatedProject ? candid_some(value.relatedProject) : candid_none(),
        name: value.name,
        createdBy: value.createdBy,
        completed: value.completed,
        dueDate: value.dueDate ? candid_some(value.dueDate) : candid_none()
    };
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    endDate?: bigint;
    value: bigint;
    orgId: OrgId;
    name: string;
    createdBy: Principal;
    startDate: bigint;
}): {
    id: string;
    endDate: [] | [bigint];
    value: bigint;
    orgId: _OrgId;
    name: string;
    createdBy: Principal;
    startDate: bigint;
} {
    return {
        id: value.id,
        endDate: value.endDate ? candid_some(value.endDate) : candid_none(),
        value: value.value,
        orgId: value.orgId,
        name: value.name,
        createdBy: value.createdBy,
        startDate: value.startDate
    };
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    value: bigint;
    orgId: OrgId;
    name: string;
    createdBy: Principal;
    stage: DealStage;
}): {
    id: string;
    value: bigint;
    orgId: _OrgId;
    name: string;
    createdBy: Principal;
    stage: _DealStage;
} {
    return {
        id: value.id,
        value: value.value,
        orgId: value.orgId,
        name: value.name,
        createdBy: value.createdBy,
        stage: to_candid_DealStage_n16(_uploadFile, _downloadFile, value.stage)
    };
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    orgId: OrgId;
    name: string;
    createdBy: Principal;
    description: string;
    phase: ProjectPhase;
}): {
    id: string;
    orgId: _OrgId;
    name: string;
    createdBy: Principal;
    description: string;
    phase: _ProjectPhase;
} {
    return {
        id: value.id,
        orgId: value.orgId,
        name: value.name,
        createdBy: value.createdBy,
        description: value.description,
        phase: to_candid_ProjectPhase_n20(_uploadFile, _downloadFile, value.phase)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    email: string;
    currentOrgId?: OrgId;
    lastName: string;
    firstName: string;
}): {
    email: string;
    currentOrgId: [] | [_OrgId];
    lastName: string;
    firstName: string;
} {
    return {
        email: value.email,
        currentOrgId: value.currentOrgId ? candid_some(value.currentOrgId) : candid_none(),
        lastName: value.lastName,
        firstName: value.firstName
    };
}
async function to_candid_record_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    orgId: OrgId;
    file: ExternalBlob;
    name: string;
    category: DocumentCategory;
}): Promise<{
    orgId: _OrgId;
    file: _ExternalBlob;
    name: string;
    category: _DocumentCategory;
}> {
    return {
        orgId: value.orgId,
        file: await to_candid_ExternalBlob_n66(_uploadFile, _downloadFile, value.file),
        name: value.name,
        category: to_candid_DocumentCategory_n67(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DealStage): {
    prospecting: null;
} | {
    closedWon: null;
} | {
    negotiation: null;
} | {
    closedLost: null;
} {
    return value == DealStage.prospecting ? {
        prospecting: null
    } : value == DealStage.closedWon ? {
        closedWon: null
    } : value == DealStage.negotiation ? {
        negotiation: null
    } : value == DealStage.closedLost ? {
        closedLost: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectPhase): {
    completed: null;
} | {
    inProgress: null;
} | {
    planning: null;
} {
    return value == ProjectPhase.completed ? {
        completed: null
    } : value == ProjectPhase.inProgress ? {
        inProgress: null
    } : value == ProjectPhase.planning ? {
        planning: null
    } : value;
}
function to_candid_variant_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentCategory): {
    projectDocs: null;
} | {
    other: null;
} | {
    marketing: null;
} | {
    legal: null;
} | {
    presentations: null;
} | {
    contracts: null;
} | {
    reports: null;
} | {
    invoices: null;
} | {
    proposals: null;
} | {
    mediaAssets: null;
} {
    return value == DocumentCategory.projectDocs ? {
        projectDocs: null
    } : value == DocumentCategory.other ? {
        other: null
    } : value == DocumentCategory.marketing ? {
        marketing: null
    } : value == DocumentCategory.legal ? {
        legal: null
    } : value == DocumentCategory.presentations ? {
        presentations: null
    } : value == DocumentCategory.contracts ? {
        contracts: null
    } : value == DocumentCategory.reports ? {
        reports: null
    } : value == DocumentCategory.invoices ? {
        invoices: null
    } : value == DocumentCategory.proposals ? {
        proposals: null
    } : value == DocumentCategory.mediaAssets ? {
        mediaAssets: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
